### ISSUE TITLE
Estimado, ya estan completos?

### ISSUE THREAD

**Issue by jjmc1987** [augustosamame/facturacion_electronica_odoo_v10#1]

**Comment by augustosamame** [comment]
Habíamos decidido cerrarlo en 5 pero podemos uno más. Me confirmas para
agregarte

**Comment by jjmc1987** [comment]
Antes de entrar Pf.  Podrías indicarme  en cuanto tiempo estaría la facturación electrónica y si abarcará también la localización de boletas notas de crédito débito etcétera.  Quedó a la espera de tus comentarios, 
PD  tu correo no está funcionando

**Comment by augustosamame** [comment]
Tenemos 2 propuestas en evaluación, una de S/. 6000 plazo de entrega 1 mes
y otra de S/.6300 plazo inmediato. Abarcará todo lo que pide la SUNAT:
factura, boleta, nota de crédito, nota de débito y notificación de baja.

Saludos,

Augusto

**Comment by jjmc1987** [comment]
Pero a lo que me refería es si en el modulo de facturación se podrá crear boletas facturas notas aparte de la declaración de la sunat, y como seria el tema del pago, como se manejará?

**Comment by augustosamame** [comment]
Claro, el módulo de facturación electrónica lo que hace es recoger lo que
el Odoo factura, trasnformarlo en los XMLs que Sunat requiere, comunicarse
con SUNAT y esperar respuesta. En el ODOO se configuran los diversos
diarios para las series de boletas y facturas, y las opciones para las
notas de crédito y débito. Hasta allí son facturas y boletas normales que
inclusive se pueden imprimir desde el Odoo. El módulo se encarga de
convertirlas en electrónicas.

El pago lo haremos entre todos según las condiciones del desarrollo. No nos
hemos puesto de acuerdo exactamente como, pero en mi opinión haríamos un
contrato entre los 6 con el desarrollador, y depositamos cada uno en la
cuenta del desarrollador. Una vez que están los pagos completos, el
desarrollador nos entrega el código del módulo. Tenemos un repositorio en
Github/Bitbucket donde estará el código y solo nosotros 6 + el
desarrollador tendremos acceso.

**Comment by jjmc1987** [comment]
Y el portal que su naturaleza solicita para que los clientes puedan ver su factura?

**Comment by jjmc1987** [comment]
Y el portal que sunat solicita para que los clientes puedan ver su factura?

**Comment by augustosamame** [comment]
El portal es un servicio que ofrece el que desarrolla la solución Odoo. Es
decir, cada uno de nosotros debemos tener un servidor nube que actúe de
portal disponible para nuestros clientes. Ningún desarrollo incluye ese
tipo de servicios, pero si incluye la recepción de la respuesta de SUNAT
para que pueda ser grabada la ruta en la base de datos del portal.

2016-11-21 13:52 GMT-05:00 jjmc1987 notifications@github.com:

**Comment by jjmc1987** [comment]
Anotamr estimado, solo quedaría revisar la reputación del programador, pero necesitaría apoyo en lo que indicaste porque soy nuevo en odoo: "En el ODOO se configuran los diversos
diarios para las series de boletas y facturas, y las opciones para las
notas de crédito y débito. Hasta allí son facturas y boletas normales que
inclusive se pueden imprimir desde el Odoo." Me podrías apoyar con esa configuración?

**Comment by augustosamame** [comment]
Hola claro, no hay ningún problema. Haz la pregunta en el Grupo Google para
que todos puedan ver la pregunta y respuesta y con gusto te indico como se
hace esa configuración.

**Comment by jjmc1987** [comment]
Listo estimado agradeceré tu apoyo con tu respuesta.

**Comment by augustosamame** [comment]
Porfa haz la pregunta como tema nuevo. Al fondo de este tema de desarrollo
no lo va a ver nadie.

2016-11-21 14:53 GMT-05:00 jjmc1987 notifications@github.com:

**Comment by jjmc1987** [comment]
Listo estimado

De antemano agradezco su apoyo

https://groups.google.com/forum/m/#!topic/openerp_peru/qMx4IrbmLdA

**Comment by jjmc1987** [comment]
Estimado considera mi nombre Jonathan Miranda jjjmcampos@gmail.com, debemos decidir ya el inicio del proyecto

**Comment by augustosamame** [comment]
Bienvenido Jonathan! Ya te agregué y contigo estamos listos para empezar.
